### PR TITLE
allow user specified variant protocols to support redshift and cockroachdb

### PR DESCRIPTION
**Pull request by talentdeficit**

### CODE REVIEW

**Comment by talentdeficit** [comment]
this is non-functional and just for discussion, see #279

**Comment by fishcakez** [comment]
This would require documenting functions that are currently `@doc false` and I am not sure if we are ready to get undressed in front of the world like that yet :S. Maybe for 1.0 but not yet.

It would prevent us from supporting super extensions for the text format because we could not introduce delimiters (and any other requirements) to the bootstrap query/type info struct. However we might already have blocked that feature by requiring the leading length when decoding, so this could be ok.

**Comment by talentdeficit** [comment]
you don't need to document `Types.bootstrap_query` you just need to declare an interface/type signature for the bootstrap query

for introducing delimiters, couldn't you just kick out to the variant module for that also?

**Comment by talentdeficit** [comment]
closing in favour of disabling re-bootstrap

**Pull request closed without merging**
