### PR TITLE
Handle errors in response to SSLRequest

### LINKED ISSUE #363: Postgrex crashes on Postgres' OOM
```
** (Postgrex.Error) ERROR 53200 (out_of_memory): out of memory 
Failed on request of size 2048. 
        (ecto) lib/ecto/adapters/sql.ex:445: Ecto.Adapters.SQL.execute_or_reset/7 
        (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5 
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4 
        (ecto) lib/ecto/repo/preloader.ex:171: Ecto.Repo.Preloader.fetch_query/8 
        (ecto) lib/ecto/repo/preloader.ex:111: Ecto.Repo.Preloader.preload_assoc/10 
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2 
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5 
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 
15:01:22.718 [error] GenServer #PID<0.496.0> terminating 
** (CaseClauseError) no case clause matching: {:ok, "E"} 
    (postgrex) lib/postgrex/protocol.ex:525: Postgrex.Protocol.ssl_recv/2 
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2 
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2 
    (connection) lib/connection.ex:741: Connection.connect/3 
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4 
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5 
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 
Last message: {:DOWN, #Reference<0.0.24641538.243800>, :process, #PID<0.18964.21>, {%Postgrex.Error{connection_id: 15359, message: nil, postgres: %{code: :out_of_memory, detail: "Failed on request of size 2048.", file: "mcxt.c", line: "768", message: "out of memory", pg_code: "53200", routine: "MemoryContextAlloc", severity: "ERROR", unknown: "ERROR"}}, [{Ecto.Adapters.SQL, :execute_or_reset, 7, [file: 'lib/ecto/adapters/sql.ex', line: 445]}, {Ecto.Repo.Queryable, :execute, 5, [file: 'lib/ecto/repo/queryable.ex', line: 130]}, {Ecto.Repo.Queryable, :all, 4, [file: 'lib/ecto/repo/queryable.ex', line: 35]}, {Ecto.Repo.Preloader, :fetch_query, 8, [file: 'lib/ecto/repo/preloader.ex', line: 171]}, {Ecto.Repo.Preloader, :preload_assoc, 10, [file: 'lib/ecto/repo/preloader.ex', line: 111]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 85]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 36]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}} 
```

@fishcakez Hi, is lack of the appropriate case clause intentional?

edit: I'm on 0.13.3

### PR DESCRIPTION
**Pull request by michalmuskala**
Closes #363

@fishcakez I'm not really sure how to test this. Any tips?

### CODE REVIEW

**Comment by fishcakez** [comment]
Can you add comment with quote from docs about ancient and shouldn't happen and then we can merge without test as not a good way to do this.

**Comment by michalmuskala** [comment]
Updated.

**Comment by aerosol** [comment]
@michalmuskala @fishcakez Thank you. Not sure if I really can, but I could try replicate this e2e with a non-ancient postgres, if you're interested.

**Comment by michalmuskala** [comment]
I tried talking to postgres people (I even subscribed to the postgres mailing list 😆 ).

I think with that handling set up, we'll be able at least to see what was the error message - before we didn't even receive it.

**Pull request merged**
