### PR TITLE
Rebootstrap on every connect

### PR DESCRIPTION
**Pull request by fishcakez**
*WORK IN PROGRESS*

@josevalim is this a suitable approach to handle new oids?

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
:shipit:

**Comment by ericmj** [comment]
Will this rebootstrap for every opened connection in a pool?

**Comment by fishcakez** [comment]
It will bootstrap types not currently bootstrapped every time a connection is opened. Therefore it is possible for multiple connections to try to bootstrap the same types, the first will win. However there should only be a small number of new types in this situation because they will have been created after the initial bootstrap. Extensions and "old" types remain from the initial lock based bootstrap.

**Pull request merged**
