### PR TITLE
provide default implementation for json/jsonb encode/decode

### PR DESCRIPTION
**Pull request by talentdeficit**

### CODE REVIEW

**Comment by fishcakez** [comment]
@ericmj what are your thoughts on effectively defaulting to text for JSON?

**Comment by ericmj** [comment]
I think it can be confusing. It should be an explicit option if we add it, maybe `library: false` or `library: :text`?

**Comment by fishcakez** [comment]
@ericmj that's a good point. I think I would prefer being explicit about the "text". Perhaps that would be confusing with because the format would be `:binary`. Should we call it `:raw` or `:binary`?

**Comment by ericmj** [comment]
I think most people consuming the package wont know about the protocol level distinction between the two encoding formats. But if we want to avoid using `:text / :binary` then I think `library: false` is preferable, but `library: :raw` would also work.

**Comment by josevalim** [comment]
:+1: for something `library: :raw`.

**Comment by josevalim** [comment]
And :+1: for it being opt-in.

**Comment by talentdeficit** [comment]
i can add an explicit selector but i think requiring this to be opt in makes it very low value and probably not worth merging

if you still have to provide your own typemodule it's only 4 lines to also provide this implementation for json. unless the default typemodule uses the default implementation i think the number of people who will use it is approximately zero

**Comment by josevalim** [comment]
@talentdeficit the number of people who would use it are all the people that for some reason do not want to encode/decode the JSON automatically. If the number of people willing to do this is zero, then you are right. :D

**Comment by talentdeficit** [comment]
i don't know about the majority of users but most of my use of json/jsonb in postgres is to offload json processing to the database rather than the application. my application just sees an opaque blob of bytes. automatically encoding/decoding for each read and write is, in some cases, an unacceptable level of overhead. i don't think that is uncommon

regardless, my point is that if this is opt in it's of very low value and should probably just be closed without merging. the intent was to provide a default for users who don't need/want to configure their own typemodule

**Comment by josevalim** [comment]
>  the intent was to provide a default for users who don't need/want to configure their own typemodule

But today you have to provide your type module as well as a custom json extension that does nothing, no?

**Comment by talentdeficit** [comment]
no. today i just provide:

```
defmodule MyApp.Json do
  def encode!(json), do: json
  def decode!(json), do: json
end
Postgrex.Types.define(MyApp.T, [], json: MyApp.Json)
```

if this pr is changed to be opt in this changes to:
```
Postgrex.Types.define(MyApp.T, [], json: :raw)
```

i don't think that's a significant enough change to warrant merging

**Comment by josevalim** [comment]
@talentdeficit I agree. We shall close this then! Thank you!

**Pull request closed without merging**
