### PR TITLE
Suppress improper list warnings

### PR DESCRIPTION
**Pull request by greg-rychlewski**
Closes https://github.com/elixir-ecto/postgrex/issues/651

I noticed a similar issue was solve here by using `generated: true`: https://github.com/elixir-ecto/postgrex/pull/556/files

Also I added some `location: :keep` that I missed in my original PR.

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by aptinio** [comment]
@josevalim, if it's not too much to ask, can we get a version bump for this?

**Comment by rubas** [comment]
Second this. This breaks CI. Thanks ❤️

**Comment by tomtaylor** [comment]
Would also love to get a release cut for this. Is that something you might be able to do @greg-rychlewski? 🙏

**Comment by wojtekmach** [comment]
v0.17.2 is out!

**Comment by tomtaylor** [comment]
@wojtekmach thanks so much!

**Pull request merged**
