### PR TITLE
pass uuid as string

### PR DESCRIPTION
**Pull request by nesQuick**
As you can see in the tests, I'd like to pass my UUIDs also represented as a string.

This PR implements this feature :)

cheers

### CODE REVIEW

**Comment by ericmj** [comment]
I'm not a fan of supporting the text formats on encode since it will always decode to the binary format.

If you want to use the text format you might want to consider adding an extension that always encodes and decodes with the text format.

**Comment by fishcakez** [comment]
I agree with @ericmj so will close this issue. However if you need any help writing an extension to use this format please feel free to reply here @nesQuick.

**Comment by nesQuick** [comment]
Thanks for the fast feedback. I wonder if there is a way other then decoders, which would allow me to transform the value before retrieval / store?

**Comment by josevalim** [comment]
@nesQuick you can always map over the data, that's how ecto does conversions.

**Pull request closed without merging**
