### PR TITLE
Update close!/3 to match spec and close/3

### LINKED ISSUE #458: Postgrex.close! returns Result struct though spec and docs declare :ok
Just that ^

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #458

### CODE REVIEW

**Comment by wojtekmach** [comment]
This patch is mostly for consistency (with spec and close/3), but can't help but wonder if we should return result struct?

it doesn't have much useful information but it's still more than just ok atom, this is what we had before:

```elixir
{:ok, pid} = Postgrex.start_link(database: "wojtek"); query = Postgrex.prepare!(pid, "SELECT now()", []); Postgrex.close!(pid, query)
%Postgrex.Result{
  columns: nil,
  command: :close,
  connection_id: 19913,
  messages: nil,
  num_rows: nil,
  rows: nil
}
```

fwiw, I guess we could always grab the result struct from LogEntry.

**Comment by josevalim** [comment]
I think the consistency here would be to actually return the result. The bang variants most often return the `value` part from `{:ok, value}`.

**Comment by wojtekmach** [comment]
Closing in favour of #461

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
