### PR TITLE
Bump deps and require elixir ~> 1.2

### PR DESCRIPTION
**Pull request by fishcakez**

### CODE REVIEW

**Comment by fishcakez** [comment]
Shall we allow db_connection `~> 1.0.0-rc.4` as well to prevent Elixir 1.2 requirement?

**Comment by josevalim** [comment]
@fishcakez I would push towards 1.2 but I will let @ericmj decide. :)

**Comment by ericmj** [comment]
@fishcakez Do what you think is right and what's easiest for you. I think you are the best person to make the decision.

**Comment by fishcakez** [comment]
I would prefer not to require the upgrade but we will still support the last 2 release of Elixir and Erlang, which is a standard range. If requested we can maintain a v0.12 branch with backported patches until Elixir 1.4.

**Pull request merged**
